
server:
  port: 8100

cloud:
  aws:
    region:
      static: eu-central-1
      auto: false

    stack:
      auto: false

    sqs:
      url: https://sqs.eu-central-1.amazonaws.com/030686510607/aws-exp-sqs
      pollingThreads: 2
      pollingRate: 1000


